### ISSUE TITLE
Fix error on send form page

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-wallet-web#1806]
```
react-dom.development.js?61bb:67 Warning: Received `false` for a non-boolean attribute `highlighted`.

If you want to write it to the DOM, pass a string instead: highlighted="false" or highlighted={value.toString()}.

If you used to conditionally omit it with highlighted={condition && value}, pass highlighted={condition ? value : undefined} instead.
    at button
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:45:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./src/components/asset-item.tsx:97:27)
    at eval (webpack-internal:///./src/components/asset-row.tsx:36:21)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:45:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/stack.esm.js:26:24)
    at Transition (webpack-internal:///./node_modules/react-transition-group/esm/Transition.js:130:30)
    at Transition (webpack-internal:///./node_modules/@stacks/ui/dist/transition/base.esm.js:13:21)
    at Fade (webpack-internal:///./node_modules/@stacks/ui/dist/transition/fade.esm.js:24:27)
    at eval (webpack-internal:///./src/pages/send-tokens/components/asset-search/asset-search.tsx:55:21)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:45:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./src/pages/send-tokens/components/asset-search/asset-search.tsx:114:25)
    at eval (webpack-internal:///./src/pages/send-tokens/components/asset-search/asset-search.tsx:205:25)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:45:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:45:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/stack.esm.js:26:24)
    at main
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:45:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:45:66)
    at eval (webpack-internal:///./node_modules/@stacks/ui/dist/box/index.esm.js:16:22)
    at PopupContainer (webpack-internal:///./src/components/popup/container.tsx:102:24)
    at SendForm (webpack-internal:///./src/pages/send-tokens/send-tokens.tsx:91:26)
    at Suspense
    at Formik (webpack-internal:///./node_modules/formik/dist/formik.esm.js:1105:19)
    at eval (webpack-internal:///./src/pages/send-tokens/send-tokens.tsx:261:92)
    at Suspense
    at eval (webpack-internal:///./src/pages/account-gate.tsx:35:23)
    at D (webpack-internal:///./node_modules/react-router/index.js:35:685)
    at _c (webpack-internal:///./src/pages/account-gate-route.tsx:15:20)
    at E (webpack-internal:///./node_modules/react-router/index.js:38:820)
    at Routes (webpack-internal:///./src/routes.tsx:73:88)
    at ErrorBoundary (webpack-internal:///./src/features/errors/error-boundary.tsx:58:86)
    at AppErrorBoundary (webpack-internal:///./src/features/errors/app-error-boundary.tsx:95:24)
    at x (webpack-internal:///./node_modules/react-router/index.js:37:23)
    at x (webpack-internal:///./node_modules/react-router-dom/index.js:43:23)
    at ColorModeProvider (webpack-internal:///./node_modules/@stacks/ui/dist/color-modes/index.esm.js:34:26)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:38:21)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-a8309070.browser.esm.js:79:64)
    at ThemeProvider (webpack-internal:///./node_modules/@stacks/ui/dist/theme-provider.esm.js:19:25)
    at App (webpack-internal:///./src/app.tsx:47:51)
printWarning @ react-dom.development.js?61bb:67
error @ react-dom.development.js?61bb:43
validateProperty$1 @ react-dom.development.js?61bb:3523
warnUnknownProperties @ react-dom.development.js?61bb:3559
validateProperties$2 @ react-dom.development.js?61bb:3583
validatePropertiesInDevelopment @ react-dom.development.js?61bb:8765
setInitialProperties @ react-dom.development.js?61bb:9041
finalizeInitialChildren @ react-dom.development.js?61bb:10201
completeWork @ react-dom.development.js?61bb:19470
completeUnitOfWork @ react-dom.development.js?61bb:22815
performUnitOfWork @ react-dom.development.js?61bb:22787
workLoopSync @ react-dom.development.js?61bb:22707
renderRootSync @ react-dom.development.js?61bb:22670
performSyncWorkOnRoot @ react-dom.development.js?61bb:22293
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
discreteUpdates$1 @ react-dom.development.js?61bb:22420
discreteUpdates @ react-dom.development.js?61bb:3756
dispatchDiscreteEvent @ react-dom.development.js?61bb:5889
[Violation] 'click' handler took 170ms
```

**Comment by beguene** [comment]
I already fixed this in a previous PR (it's in main branch now). https://github.com/blockstack/stacks-wallet-web/commit/77032ee544b10cf347efb8f38d73ef08c84eda9d

Closing.
